name: Danny Englander
markdown: redcarpet
baseurl: ""
exclude: [
  .git,
  .gitignore,
  .DS_Store,
  assets,
  CNAME,
  svg-icons,
  svg-decorations,
  sass,
  package.json,
  Gruntfile.js,
  gruntfile.js,
  node_modules,
  package.json,
  readme.md,
  node_modules
]

excerpt_separator: <!--more-->