name: Danny Englander
markdown: redcarpet
highlighter: pygments
baseurl: "/libsass-experiments"
permalink: pretty
relative_permalinks: true
exclude: [
  .git,
  .gitignore,
  .DS_Store,
  assets,
  CNAME,
  svg-icons,
  svg-decorations,
  sass,
  package.json,
  Gruntfile.js,
  gruntfile.js,
  node_modules,
  package.json,
  readme.md,
  README.md,
  node_modules
]

excerpt_separator: <!--more-->